# Copyright (c) 2021 by Mario O. Villarroel - ElcanSoftware
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in aeromanager_models.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# Annotate models
gem 'annotate', '~> 3.1', '>= 3.1.1', group: %i[development test]
# To use a debugger
gem 'byebug', group: %i[development test]
# RSPEC tests instead of regular
gem 'rspec-rails', group: %i[development test]
# ERD generation support
gem 'rails-erd', group: :development
